AssetTrackingProjectATP/flaskmvc

- App/controllers/location.py
- App/models/location.py
> Location-Controller

- App/controllers/assignee.py
> Assignee Controller

- App/models/history.py
> History Model

- App/models/user.py
updated user model to include a username column. updated init function and json function
> Edited user model to include both email and username

- App/controllers/assignee.py
Get assignee by first name and last name
> Get assignee by first name and last name

- App/controllers/asset.py
Allows new assignees to be added via the add_asset method
> Allows new assignees to be added via the add_asset method

- App/controllers/assignee.py
> Assignee with Room_ID

- App/controllers/asset.py
- App/models/asset.py
Updates the Asset model and controller to better reflect model diagram
> Update asset model

- App/controllers/assetassignment.py
- App/models/assetassignment.py
AssetAssignment Model and Controller
> AssetAssignment Model and Controller

- App/controllers/building.py
- App/controllers/floor.py
- App/models/floor.py
added the model and controller for the floor table
> Floor-model-and-controller

- App/controllers/room.py
- App/models/room.py
added room model and room controller
> Room-model-and-controller

- App/controllers/asset.py
- wsgi.py
Commands to allow multiple assets to be viewed by room id
> Create cli commands asset

- wsgi.py
Populated wsgi.py with sample data for all methods
> sample data for all methods

- App/models/acquisition.py
> creates a model for provider

- App/tests/test_app.py
Tests for building, floor, room
> Location tests

- App/controllers/asset.py
- App/models/asset.py
- App/tests/test_app.py
- wsgi.py
Adds functionality for assets to include the last location recorded and fixes user unit and integration tests
> Add functionality for current location and fixes tests

- App/tests/test_app.py
Unit and Integration Tests for assignee and assetassignment
> Assignee tests

- App/controllers/asset.py
- App/tests/test_app.py
- wsgi.py
> Scanevent tests

- App/controllers/initialize.py
- App/templates/inventory.html
fixes initialize and creates a button for the Add csv controller
> Csv upload

- App/controllers/asset.py
- App/tests/test_app.py
First batch of asset integration tests
> Asset integration tests

- App/CSVsample.csv
- App/controllers/asset.py
- App/controllers/initialize.py
- App/templates/settings.html
- App/views/__init__.py
- App/views/settings.py
- CSVsample.csv
- wsgi.py
> Settings page 2nd attempt

- .github/workflows/deploy.yml
Automatically deploys the main branch on render
> automatically deploys the main branch on render

- App/controllers/building.py
- App/controllers/floor.py
- App/controllers/room.py
- App/static/js/settings.js
- App/templates/settings.html
- App/views/settings.py
fixed bug where editting a building,floor,room will cause a duplicate where the duplicate will have nothing associated with it
> Error fixing

- App/static/js/discrepancy.js
- App/templates/asset.html
- App/templates/discrepancy.html
- App/views/discrepancy.py
added the ability to add a optional note when reassigning an asset
> Note  functionality

- App/controllers/asset.py
- App/controllers/room.py
- App/views/settings.py
uploading csv functionality for asset and location.
user can now upload a csv to bulk upload locations and/or assets
> Update csv upload room

- App/controllers/assignee.py
- App/tests/test_app.py
Adds a controller to retrieve an assignee's name by assignee's id
> Create controller to get assignee's full name, with test
